import type { Metadata } from "next";
import "./globals.css";
import { geistSans, geistMono, manrope } from "./fonts";
import Header from "@/component/shared/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.className} antialiased`}>
        <Header />
        <main className="">{children}</main>
      </body>
    </html>
  );
}
